### ISSUE TITLE
Combine needs a mass value for the signal process

### ISSUE THREAD

**Issue by adewit** [cms-analysis/CombineHarvester#1]
For some limit calculation methods, combine needs the signal process to have a mass value specified in the shape file. CH currently lets you make a datacard + shape file without mass value, if this is done it would be nice to assign the signal process a dummy mass value so that the datacard can be used with all combine methods.

**Comment by ajgilbert** [comment]
Just to check I understand the issue (also reported by @thomas-mueller): the problem is purely on the CH side, in that it requires signal processes to have a valid numeric mass value to write a datacard? This then has to be passed to text2workspace with -m. What we want is a way to write signal processes without the $MASS pattern. Is that correct or is there another problem?

**Comment by adewit** [comment]
Ah yes, it is only that - so yes, we want a way to write signal processes without the $MASS pattern.

**Comment by ajgilbert** [comment]
@adewit @ffrensch @thomas-mueller 
i've tried to fix this on the ch-oct-15 branch - let me know if it works ok. now if you set a signal process mass to "*" it shouldn't put $MASS in the mapping pattern.

**Comment by adewit** [comment]
Great! This works fine :-)
